CREATE TABLE IF NOT EXISTS material_history (
                                  quantity integer not null,
                                  stock_after_transaction integer not null,
                                  id bigint generated by default as identity,
                                  material_id bigint not null,
                                  transaction_date timestamp(6) not null,
                                  remarks varchar(255),
                                  type varchar(255) not null check ((type in ('INCOMING','OUTGOING','RETURN','ADJUSTMENT'))),
                                  worker varchar(255),
                                  primary key (id)
);

CREATE TABLE IF NOT EXISTS materials (
                           current_stock integer not null,
                           safety_stock integer not null,
                           unit_price float(53) not null,
                           created_at timestamp(6),
                           id bigint generated by default as identity,
                           updated_at timestamp(6),
                           category varchar(255) not null,
                           item_code varchar(255) not null unique,
                           item_name varchar(255) not null,
                           primary key (id)
);
CREATE TABLE IF NOT EXISTS machines (
                          production_count integer not null,
                          rpm integer not null,
                          temperature float(53) not null,
                          vibration float(53) not null,
                          client varchar(255),
                          id varchar(255) not null,
                          last_updated varchar(255),
                          name varchar(255) not null,
                          order_name varchar(255),
                          status varchar(255) not null,
                          type varchar(255) not null,
                          primary key (id)
);
CREATE TABLE IF NOT EXISTS members (
                         password varchar(255) not null,
                         role varchar(255) not null,
                         username varchar(255) not null,
                         primary key (username)
);

CREATE TABLE IF NOT EXISTS machine_logs (
      production_count integer,
      rpm integer not null,
      temperature float(53) not null,
      vibration float(53) not null,
      log_id bigint generated by default as identity,
      recorded_at timestamp(6),
      machine_id varchar(255) not null,
      order_name varchar(255),
      status varchar(255),
      primary key (log_id)
);

CREATE INDEX IF NOT EXISTS idx_machine_logs_time ON machine_logs(machine_id, recorded_at DESC);

-- [기계 데이터] PCB 파운드리 기계 목록 초기화
INSERT INTO machines (id, name, type, status, client, order_name, temperature, rpm, vibration, production_count, last_updated)
VALUES
    ('m1', 'Solder Printer #1', 'PRINTER', 'RUNNING', 'Samsung Electronics', 'Galaxy S24 Mainboard', 25.5, 1500, 1.2, 1540, NOW()),
    ('m2', 'Reflow Oven Zone-1', 'OVEN', 'RUNNING', 'LG Electronics', 'OLED TV Power Module', 240.5, 1200, 0.8, 0, NOW()),
    ('m3', 'AOI Inspector (Vision)', 'INSPECTOR', 'STOPPED', 'NVIDIA', 'H100 GPU Substrate', 30.0, 0, 0.2, 11950, NOW()),
    ('m4', 'Auto Unloader', 'UNLOADER', 'STOPPED', 'Apple', 'iPhone 16 Pro Logic Board', 28.0, 0, 0.5, 500, NOW()),
    ('m5', 'High Speed Mounter', 'MOUNTER', 'RUNNING', 'Tesla', 'Model Y ECU Board', 45.2, 2500, 3.5, 32000, NOW())
ON CONFLICT (id) -- id가 이미 존재하면 (PK 충돌 시)
    DO UPDATE SET
                  name = EXCLUDED.name,
                  type = EXCLUDED.type,
                  status = EXCLUDED.status,
                  client = EXCLUDED.client,
                  order_name = EXCLUDED.order_name,
                  temperature = EXCLUDED.temperature,
                  rpm = EXCLUDED.rpm,
                  vibration = EXCLUDED.vibration,
                  production_count = EXCLUDED.production_count,
                  last_updated = NOW(); -- 업데이트 시간 갱신

-- [자재 데이터] PCB 파운드리 자재 목록 초기화
INSERT INTO materials (item_code, item_name, category, current_stock, safety_stock, unit, supplier, unit_price, created_at, updated_at)
VALUES
    ('MAT-CCL-01', 'FR-4 1.6T Copper Board', 'RAW', 500, 100, 'Sheet', 'Doosan Electro', 15000, NOW(), NOW()),
    ('MAT-CHEM-01', 'Ferric Chloride Etchant', 'CHEMICAL', 200, 50, 'Liter', 'LG Chem', 5000, NOW(), NOW()),
    ('MAT-SLD-05', 'Lead-Free Solder Paste', 'RAW', 50, 10, 'KG', 'Senju Metal', 120000, NOW(), NOW()),
    ('PART-TSLA-ECU', 'Tesla ECU Control Chip', 'CLIENT', 5000, 1000, 'EA', 'Tesla', 0, NOW(), NOW()),
    ('PART-SAMSUNG-AP', 'Exynos 2400 Processor', 'CLIENT', 2000, 500, 'EA', 'Samsung Electronics', 0, NOW(), NOW())
ON CONFLICT (item_code) -- id가 아닌 유니크 키(item_code)를 기준으로 충돌 확인
    DO UPDATE SET
      item_name = EXCLUDED.item_name,
      category = EXCLUDED.category,
      current_stock = EXCLUDED.current_stock,
      safety_stock = EXCLUDED.safety_stock,
      unit = EXCLUDED.unit,
      supplier = EXCLUDED.supplier,
      unit_price = EXCLUDED.unit_price,
      updated_at = NOW(); -- 수정 시간은 현재 시간으로 갱신



-- 초기 관리자(Admin) 계정 삽입
-- 아이디: admin, 비번: 1234 (앞에 {noop}은 "암호화 안 된 문자 그대로"라는 뜻)
INSERT INTO members (username, password, role)
VALUES ('admin', '{noop}1234', 'ROLE_ADMIN')
ON CONFLICT (username) DO NOTHING;